"""control plane

Revision ID: 68b309b0fac4
Revises:
Create Date: 2026-10-06 11:11:08.127413
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate emits sqlmodel.sql.sqltypes.*)
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "68b309b0fac4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connection",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dsn_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("dsn_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("wrapped_data_key", sa.LargeBinary(), nullable=False),
        sa.Column("wrap_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("algorithm", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("statement_timeout_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verify_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connection")),
        sa.UniqueConstraint("workspace_id", "name", name="uq_connection_name"),
    )
    op.create_index(
        op.f("ix_connection_workspace_id"), "connection", ["workspace_id"], unique=False
    )
    op.create_table(
        "connector",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("spec", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column(
            "auth_kind", sa.Enum("none", "bearer", "header", name="authkind"), nullable=False
        ),
        sa.Column("auth_header_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secret_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("secret_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("wrapped_data_key", sa.LargeBinary(), nullable=True),
        sa.Column("wrap_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("key_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("algorithm", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector")),
        sa.UniqueConstraint("workspace_id", "name", name="uq_connector_name"),
    )
    op.create_index(op.f("ix_connector_workspace_id"), "connector", ["workspace_id"], unique=False)
    op.create_table(
        "dedup_counter",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dedup_counter")),
        sa.UniqueConstraint("workspace_id", "rule_name", "dedup_key", name="uq_dedup_counter"),
    )
    op.create_table(
        "dedup_occurrence",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("occurrence_id", sa.Text(), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dedup_occurrence")),
        sa.UniqueConstraint(
            "workspace_id", "rule_name", "dedup_key", "occurrence_id", name="uq_dedup_occurrence"
        ),
    )
    op.create_table(
        "definition_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("yaml_text", sa.Text(), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_definition_version")),
        sa.UniqueConstraint("workspace_id", "version", name="uq_definition_version"),
    )
    op.create_index(
        op.f("ix_definition_version_checksum"), "definition_version", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_definition_version_workspace_id"),
        "definition_version",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "recipient_budget",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipient_budget")),
        sa.UniqueConstraint(
            "workspace_id", "recipient", "window_start", name="uq_recipient_budget"
        ),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mode", sa.Enum("shadow", "live", name="mode"), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("matched_rows", sa.Integer(), nullable=False),
        sa.Column("fires_new", sa.Integer(), nullable=False),
        sa.Column("fires_suppressed", sa.Integer(), nullable=False),
        sa.Column("null_event_time_rows", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("running", "ok", "failed", name="runstatus"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
    )
    op.create_index(op.f("ix_run_trigger_name"), "run", ["trigger_name"], unique=False)
    op.create_index(op.f("ix_run_workspace_id"), "run", ["workspace_id"], unique=False)
    op.create_table(
        "workspace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("halted", sa.Boolean(), nullable=False),
        sa.Column("halted_reason", sa.Text(), nullable=True),
        sa.Column("cap_per_recipient", sa.Integer(), nullable=False),
        sa.Column("cap_window_hours", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace")),
    )
    op.create_table(
        "connector_action",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path_template", sa.Text(), nullable=True),
        sa.Column("body_template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("headers_template", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("retry_on", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connector.id"],
            name="fk_connector_action_connector",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_action")),
        sa.UniqueConstraint("connector_id", "name", name="uq_connector_action_name"),
    )
    op.create_table(
        "fire",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("dedup_bucket", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_fire_run_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fire")),
        sa.UniqueConstraint(
            "workspace_id", "rule_name", "dedup_key", "dedup_bucket", name="uq_fire_dedup"
        ),
    )
    op.create_index(
        "ix_fire_recent", "fire", ["workspace_id", "rule_name", "fired_at"], unique=False
    )
    op.create_table(
        "rule_state",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trigger_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mode", sa.Enum("shadow", "live", name="mode"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("definition_checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("definition_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_version_id"],
            ["definition_version.id"],
            name=op.f("fk_rule_state_definition_version_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_state")),
        sa.UniqueConstraint("workspace_id", "rule_name", name="uq_rule_state_name"),
    )
    op.create_index(
        op.f("ix_rule_state_trigger_name"), "rule_state", ["trigger_name"], unique=False
    )
    op.create_index(
        op.f("ix_rule_state_workspace_id"), "rule_state", ["workspace_id"], unique=False
    )
    op.create_table(
        "trigger_state",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lookback_seconds", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connection.id"],
            name=op.f("fk_trigger_state_connection_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trigger_state")),
        sa.UniqueConstraint("workspace_id", "trigger_name", name="uq_trigger_state_name"),
    )
    op.create_index(
        op.f("ix_trigger_state_workspace_id"), "trigger_state", ["workspace_id"], unique=False
    )
    op.create_table(
        "delivery",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("fire_id", sa.BigInteger(), nullable=True),
        sa.Column("rule_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mode", sa.Enum("shadow", "live", name="mode"), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("connector_action_id", sa.Uuid(), nullable=True),
        sa.Column("rendered", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_url", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", "suppressed", name="deliverystatus"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("suppressed_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["connector_action_id"],
            ["connector_action.id"],
            name="fk_delivery_connector_action",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["fire_id"], ["fire.id"], name=op.f("fk_delivery_fire_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery")),
    )
    op.create_index(op.f("ix_delivery_recipient"), "delivery", ["recipient"], unique=False)
    op.create_index(op.f("ix_delivery_rule_name"), "delivery", ["rule_name"], unique=False)
    op.create_index(op.f("ix_delivery_workspace_id"), "delivery", ["workspace_id"], unique=False)
    op.create_table(
        "rule_binding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("connector_action_id", sa.Uuid(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recipient_template", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_action_id"],
            ["connector_action.id"],
            name=op.f("fk_rule_binding_connector_action_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_binding")),
        sa.UniqueConstraint(
            "workspace_id", "rule_name", "connector_action_id", name="uq_rule_binding"
        ),
    )
    op.create_index(op.f("ix_rule_binding_rule_name"), "rule_binding", ["rule_name"], unique=False)
    op.create_index(
        op.f("ix_rule_binding_workspace_id"), "rule_binding", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rule_binding_workspace_id"), table_name="rule_binding")
    op.drop_index(op.f("ix_rule_binding_rule_name"), table_name="rule_binding")
    op.drop_table("rule_binding")
    op.drop_index(op.f("ix_delivery_workspace_id"), table_name="delivery")
    op.drop_index(op.f("ix_delivery_rule_name"), table_name="delivery")
    op.drop_index(op.f("ix_delivery_recipient"), table_name="delivery")
    op.drop_table("delivery")
    op.drop_index(op.f("ix_trigger_state_workspace_id"), table_name="trigger_state")
    op.drop_table("trigger_state")
    op.drop_index(op.f("ix_rule_state_workspace_id"), table_name="rule_state")
    op.drop_index(op.f("ix_rule_state_trigger_name"), table_name="rule_state")
    op.drop_table("rule_state")
    op.drop_index("ix_fire_recent", table_name="fire")
    op.drop_table("fire")
    op.drop_table("connector_action")
    op.drop_table("workspace")
    op.drop_index(op.f("ix_run_workspace_id"), table_name="run")
    op.drop_index(op.f("ix_run_trigger_name"), table_name="run")
    op.drop_table("run")
    op.drop_table("recipient_budget")
    op.drop_index(op.f("ix_definition_version_workspace_id"), table_name="definition_version")
    op.drop_index(op.f("ix_definition_version_checksum"), table_name="definition_version")
    op.drop_table("definition_version")
    op.drop_table("dedup_occurrence")
    op.drop_table("dedup_counter")
    op.drop_index(op.f("ix_connector_workspace_id"), table_name="connector")
    op.drop_table("connector")
    op.drop_index(op.f("ix_connection_workspace_id"), table_name="connection")
    op.drop_table("connection")
    # ### end Alembic commands ###

    # Alembic creates these enum types implicitly with the columns that use
    # them, but never drops them -- so a downgrade followed by an upgrade
    # fails with "type already exists". Dropping them here is what makes this
    # migration genuinely reversible.
    for enum_name in ("authkind", "deliverystatus", "mode", "runstatus"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
