"""workspace lifecycle for hosted visitors

Revision ID: 926b40ca4d46
Revises: 64f18bf0503e
Create Date: 2026-10-07 16:16:54.382233
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate emits sqlmodel.sql.sqltypes.*)
from alembic import op

revision: str = "926b40ca4d46"
down_revision: str | None = "64f18bf0503e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # A server default, because existing installs already have a workspace
    # row, and a NOT NULL column without one cannot be added to it.
    op.add_column(
        "workspace",
        sa.Column("ephemeral", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("workspace", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "last_seen_at")
    op.drop_column("workspace", "ephemeral")
    # ### end Alembic commands ###
