"""a run has no mode of its own

A poll fans out to every rule on the trigger, and those carry their own modes.
The single `mode` here was a leftover from when mode lived on the trigger: it
was never set after the row was created, so it reported `shadow` for every run
ever made -- including ones where a live rule sent. Whether anything left the
building is now answered by counting deliveries.

The downgrade restores the column with its old default, which is as faithful
as it can be: the information it claimed to hold never existed.

Revision ID: fc38b58a2ab1
Revises: 9c6490af597b
Create Date: 2026-10-06 19:01:59.139743
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate emits sqlmodel.sql.sqltypes.*)
from alembic import op

revision: str = "fc38b58a2ab1"
down_revision: str | None = "9c6490af597b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("run", "mode")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "run",
        sa.Column("mode", sa.String(), nullable=False, server_default="shadow"),
    )
    op.alter_column("run", "mode", server_default=None)
